[msg GoToHotsprings]
[s][vp 1 0 0 0]> You all have a relaxing time in the hot springs...[n][vAuto 65535][e]

[msg MSG_COSTUME_000]
[s][vp 1 0 0 0]> Afterwards you changed into a yukata and[n]returned to the room...[n][vAuto 65535][w][e]
[s][vp 1 0 0 0]> Obtained [itemVar 3 65535 0].[n][vAuto 65535][w][e]

[msg NightEnd]
[s][vp 1 0 0 0]> The rest of the night at the Amagi Inn passes by...[n][vAuto 65535][e]